openapi: 3.0.1
info:
  title: Sample API
  version: 1.0.0
servers:
  - url: https://example.com
  - url: https://opendart.fss.or.kr
paths:
  /api/list.json:
    get:
      summary: 공시 목록 조회
      parameters:
        - name: crtfc_key
          in: query
          required: true
          schema:
            type: string
          description: 인증키
        - name: corp_code
          in: query
          required: false
          schema:
            type: string
        - name: bgn_de
          in: query
          required: false
          schema:
            type: string
        - name: end_de
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: 공시목록 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "000"
                    description: 응답 상태 코드
                  message:
                    type: string
                    example: "정상"
                    description: 응답 메시지
                  page_no:
                    type: integer
                    example: 1
                    description: 현재 페이지 번호
                  page_count:
                    type: integer
                    example: 10
                    description: 한 페이지당 건수
                  total_count:
                    type: integer
                    example: 217
                    description: 전체 건수
                  total_page:
                    type: integer
                    example: 22
                    description: 전체 페이지 수
                  list:
                    type: array
                    description: 공시 목록
                    items:
                      type: object
                      properties:
                        corp_code:
                          type: string
                          example: "00120182"
                          description: 회사 고유번호
                        corp_name:
                          type: string
                          example: "NH투자증권"
                          description: 회사명
                        stock_code:
                          type: string
                          example: "005940"
                          description: 종목코드
                        corp_cls:
                          type: string
                          example: "Y"
                          description: 상장구분 (Y/N/K)
                        report_nm:
                          type: string
                          example: "일괄신고추가서류(파생결합증권)"
                          description: 보고서명
                        rcept_no:
                          type: string
                          example: "20200117000559"
                          description: 접수번호
                        flr_nm:
                          type: string
                          example: "NH투자증권"
                          description: 공시 제출자
                        rcept_dt:
                          type: string
                          example: "20200117"
                          description: 접수일자 (YYYYMMDD)
                        rm:
                          type: string
                          example: "유"
        '400':
          description: 잘못된 요청. 파라미터 확인 필요.
        '500':
          description: 서버 내부 오류
      operationId: getApiListJson
  /hello:
    get:
      summary: Hello world
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello, world!
      operationId: getHello
